### ISSUE TITLE
牛

### ISSUE THREAD

**Issue by albert-jin** [zhanghaok/BERT-MRC-NER#1]
太强啦，同学，我在创新港鸿理楼，你也是电信学部的嘛，今年ACL2023准备好稿子了嘛嘻嘻

**Comment by zhanghaok** [comment]
> 太强啦，同学，我在创新港鸿理楼，你也是电信学部的嘛，今年ACL2023准备好稿子了嘛嘻嘻

别别别，我这个也是跟着别人实现的哈哈😂，是的我也在4号巨构

**Comment by albert-jin** [comment]
加个微信，我有点忙需要你帮，可以给你致谢里面加个名儿，ii嘻嘻&nbsp;
微信&nbsp; jinweiqiang0309

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月14日(周五) 下午2:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhanghaok/BERT-MRC-NER] 牛 (Issue #1)




  
太强啦，同学，我在创新港鸿理楼，你也是电信学部的嘛，今年ACL2023准备好稿子了嘛嘻嘻
  
别别别，我这个也是跟着别人实现的哈哈😂，是的我也在4号巨构
